CASE DeviceModel
    WHEN 'iPhone1,1' THEN 'iPhone'
    WHEN 'iPhone1,2' THEN 'iPhone 3G'
    WHEN 'iPhone2,1' THEN 'iPhone 3GS'
    WHEN 'iPhone3,1' THEN 'iPhone 4'
    WHEN 'iPhone3,2' THEN 'iPhone 4 GSM Rev A'
    WHEN 'iPhone3,3' THEN 'iPhone 4 CDMA'
    WHEN 'iPhone4,1' THEN 'iPhone 4S'
    WHEN 'iPhone5,1' THEN 'iPhone 5 (GSM)'
    WHEN 'iPhone5,2' THEN 'iPhone 5 (GSM+CDMA)'
    WHEN 'iPhone5,3' THEN 'iPhone 5C (GSM)'
    WHEN 'iPhone5,4' THEN 'iPhone 5C (Global)'
    WHEN 'iPhone6,1' THEN 'iPhone 5S (GSM)'
    WHEN 'iPhone6,2' THEN 'iPhone 5S (Global)'
    WHEN 'iPhone7,1' THEN 'iPhone 6 Plus'
    WHEN 'iPhone7,2' THEN 'iPhone 6'
    WHEN 'iPhone8,1' THEN 'iPhone 6s'
    WHEN 'iPhone8,2' THEN 'iPhone 6s Plus'
    WHEN 'iPhone8,4' THEN 'iPhone SE (GSM)'
    WHEN 'iPhone9,1' THEN 'iPhone 7'
    WHEN 'iPhone9,2' THEN 'iPhone 7 Plus'
    WHEN 'iPhone9,3' THEN 'iPhone 7'
    WHEN 'iPhone9,4' THEN 'iPhone 7 Plus'
    WHEN 'iPhone10,1' THEN 'iPhone 8'
    WHEN 'iPhone10,2' THEN 'iPhone 8 Plus'
    WHEN 'iPhone10,3' THEN 'iPhone X Global'
    WHEN 'iPhone10,4' THEN 'iPhone 8'
    WHEN 'iPhone10,5' THEN 'iPhone 8 Plus'
    WHEN 'iPhone10,6' THEN 'iPhone X GSM'
    WHEN 'iPhone11,2' THEN 'iPhone XS'
    WHEN 'iPhone11,4' THEN 'iPhone XS Max'
    WHEN 'iPhone11,6' THEN 'iPhone XS Max Global'
    WHEN 'iPhone11,8' THEN 'iPhone XR'
    WHEN 'iPhone12,1' THEN 'iPhone 11'
    WHEN 'iPhone12,3' THEN 'iPhone 11 Pro'
    WHEN 'iPhone12,5' THEN 'iPhone 11 Pro Max'
    WHEN 'iPhone12,8' THEN 'iPhone SE 2nd Gen'
    WHEN 'iPhone13,1' THEN 'iPhone 12 Mini'
    WHEN 'iPhone13,2' THEN 'iPhone 12'
    WHEN 'iPhone13,3' THEN 'iPhone 12 Pro'
    WHEN 'iPhone13,4' THEN 'iPhone 12 Pro Max'
    WHEN 'iPhone14,2' THEN 'iPhone 13 Pro'
    WHEN 'iPhone14,3' THEN 'iPhone 13 Pro Max'
    WHEN 'iPhone14,4' THEN 'iPhone 13 Mini'
    WHEN 'iPhone14,5' THEN 'iPhone 13'
    WHEN 'iPhone14,6' THEN 'iPhone SE 3rd Gen'
    WHEN 'iPhone14,7' THEN 'iPhone 14'
    WHEN 'iPhone14,8' THEN 'iPhone 14 Plus'
    WHEN 'iPhone15,2' THEN 'iPhone 14 Pro'
    WHEN 'iPhone15,3' THEN 'iPhone 14 Pro Max'
    WHEN 'iPhone15,4' THEN 'iPhone 15'
    WHEN 'iPhone15,5' THEN 'iPhone 15 Plus'
    WHEN 'iPhone16,1' THEN 'iPhone 15 Pro'
    WHEN 'iPhone16,2' THEN 'iPhone 15 Pro Max'
    WHEN 'iPad2,3' THEN '2nd Gen iPad CDMA'
    WHEN 'iPad2,4' THEN '2nd Gen iPad New Revision'
    WHEN 'iPad3,1' THEN '3rd Gen iPad'
    WHEN 'iPad3,2' THEN '3rd Gen iPad CDMA'
    WHEN 'iPad3,3' THEN '3rd Gen iPad GSM'
    WHEN 'iPad2,5' THEN 'iPad mini'
    WHEN 'iPad2,6' THEN 'iPad mini GSM+LTE'
    WHEN 'iPad2,7' THEN 'iPad mini CDMA+LTE'
    WHEN 'iPad3,4' THEN '4th Gen iPad'
    WHEN 'iPad3,5' THEN '4th Gen iPad GSM+LTE'
    WHEN 'iPad3,6' THEN '4th Gen iPad CDMA+LTE'
    WHEN 'iPad4,1' THEN 'iPad Air (WiFi)'
    WHEN 'iPad4,2' THEN 'iPad Air (GSM+CDMA)'
    WHEN 'iPad4,3' THEN '1st Gen iPad Air (China)'
    WHEN 'iPad4,4' THEN 'iPad mini Retina (WiFi)'
    WHEN 'iPad4,5' THEN 'iPad mini Retina (GSM+CDMA)'
    WHEN 'iPad4,6' THEN 'iPad mini Retina (China)'
    WHEN 'iPad4,7' THEN 'iPad mini 3 (WiFi)'
    WHEN 'iPad4,8' THEN 'iPad mini 3 (GSM+CDMA)'
    WHEN 'iPad4,9' THEN 'iPad Mini 3 (China)'
    WHEN 'iPad5,1' THEN 'iPad mini 4 (WiFi)'
    WHEN 'iPad5,2' THEN '4th Gen iPad mini (WiFi+Cellular)'
    WHEN 'iPad5,3' THEN 'iPad Air 2 (WiFi)'
    WHEN 'iPad5,4' THEN 'iPad Air 2 (Cellular)'
    WHEN 'iPad6,3' THEN 'iPad Pro (9.7 inch, WiFi)'
    WHEN 'iPad6,4' THEN 'iPad Pro (9.7 inch, WiFi+LTE)'
    WHEN 'iPad6,7' THEN 'iPad Pro (12.9 inch, WiFi)'
    WHEN 'iPad6,8' THEN 'iPad Pro (12.9 inch, WiFi+LTE)'
    WHEN 'iPad6,11' THEN 'iPad (2017)'
    WHEN 'iPad6,12' THEN 'iPad (2017)'
    WHEN 'iPad7,1' THEN 'iPad Pro 2nd Gen (WiFi)'
    WHEN 'iPad7,2' THEN 'iPad Pro 2nd Gen (WiFi+Cellular)'
    WHEN 'iPad7,3' THEN 'iPad Pro 10.5-inch 2nd Gen'
    WHEN 'iPad7,4' THEN 'iPad Pro 10.5-inch 2nd Gen'
    WHEN 'iPad7,5' THEN 'iPad 6th Gen (WiFi)'
    WHEN 'iPad7,6' THEN 'iPad 6th Gen (WiFi+Cellular)'
    WHEN 'iPad7,11' THEN 'iPad 7th Gen 10.2-inch (WiFi)'
    WHEN 'iPad7,12' THEN 'iPad 7th Gen 10.2-inch (WiFi+Cellular)'
    WHEN 'iPad8,1' THEN 'iPad Pro 11 inch 3rd Gen (WiFi)'
    WHEN 'iPad8,2' THEN 'iPad Pro 11 inch 3rd Gen (1TB, WiFi)'
    WHEN 'iPad8,3' THEN 'iPad Pro 11 inch 3rd Gen (WiFi+Cellular)'
    WHEN 'iPad8,4' THEN 'iPad Pro 11 inch 3rd Gen (1TB, WiFi+Cellular)'
    WHEN 'iPad8,5' THEN 'iPad Pro 12.9 inch 3rd Gen (WiFi)'
    WHEN 'iPad8,6' THEN 'iPad Pro 12.9 inch 3rd Gen (1TB, WiFi)'
    WHEN 'iPad8,7' THEN 'iPad Pro 12.9 inch 3rd Gen (WiFi+Cellular)'
    WHEN 'iPad8,8' THEN 'iPad Pro 12.9 inch 3rd Gen (1TB, WiFi+Cellular)'
    WHEN 'iPad8,9' THEN 'iPad Pro 11 inch 4th Gen (WiFi)'
    WHEN 'iPad8,10' THEN 'iPad Pro 11 inch 4th Gen (WiFi+Cellular)'
    WHEN 'iPad8,11' THEN 'iPad Pro 12.9 inch 4th Gen (WiFi)'
    WHEN 'iPad8,12' THEN 'iPad Pro 12.9 inch 4th Gen (WiFi+Cellular)'
    WHEN 'iPad11,1' THEN 'iPad mini 5th Gen (WiFi)'
    WHEN 'iPad11,2' THEN 'iPad mini 5th Gen (WiFi+Cellular)'
    WHEN 'iPad11,3' THEN 'iPad Air 3rd Gen (WiFi)'
    WHEN 'iPad11,4' THEN 'iPad Air 3rd Gen (WiFi+Cellular)'
    WHEN 'iPad11,6' THEN 'iPad 8th Gen (WiFi)'
    WHEN 'iPad11,7' THEN 'iPad 8th Gen (WiFi+Cellular)'
    WHEN 'iPad12,1' THEN 'iPad 9th Gen (WiFi)'
    WHEN 'iPad12,2' THEN 'iPad 9th Gen (WiFi+Cellular)'
    WHEN 'iPad13,1' THEN 'iPad Air 4th Gen (WiFi)'
    WHEN 'iPad13,2' THEN 'iPad Air 4th Gen (WiFi+Cellular)'
    WHEN 'iPad13,4' THEN 'iPad Pro 11 inch 3rd Gen (WiFi)'
    WHEN 'iPad13,5' THEN 'iPad Pro 11 inch 3rd Gen (1TB, WiFi)'
    WHEN 'iPad13,6' THEN 'iPad Pro 11 inch 3rd Gen (WiFi+Cellular)'
    WHEN 'iPad13,7' THEN 'iPad Pro 11 inch 3rd Gen (1TB, WiFi+Cellular)'
    WHEN 'iPad13,8' THEN 'iPad Pro 12.9 inch 3rd Gen (WiFi)'
    WHEN 'iPad13,9' THEN 'iPad Pro 12.9 inch 3rd Gen (1TB, WiFi)'
    WHEN 'iPad13,10' THEN 'iPad Pro 12.9 inch 3rd Gen (WiFi+Cellular)'
    WHEN 'iPad13,11' THEN 'iPad Pro 12.9 inch 3rd Gen (1TB, WiFi+Cellular)'
    WHEN 'iPad13,16' THEN 'iPad Air 5th Gen (WiFi)'
    WHEN 'iPad13,17' THEN 'iPad Air 5th Gen (WiFi+Cellular)'
    WHEN 'iPad13,18' THEN 'iPad 10th Gen (WiFi)'
    WHEN 'iPad13,19' THEN 'iPad 10th Gen (WiFi+Cellular)'
    WHEN 'iPad14,1' THEN 'iPad mini 6th Gen (WiFi)'
    WHEN 'iPad14,2' THEN 'iPad mini 6th Gen (WiFi+Cellular)'
    WHEN 'iPad14,3' THEN 'iPad Pro 11 inch 4th Gen (WiFi)'
    WHEN 'iPad14,4' THEN 'iPad Pro 11 inch 4th Gen (WiFi+Cellular)'
    WHEN 'iPad14,5' THEN 'iPad Pro 12.9 inch 6th Gen (WiFi)'
    WHEN 'iPad14,6' THEN 'iPad Pro 12.9 inch 6th Gen (WiFi+Cellular)'
Else DeviceModel END As DeviceModel 


// If you have the device model but don't know the device name and want to find out, this code is perfect for you!
